### PR TITLE
Updated to current irclib API; added non-UTF8 decoder.

### PR DESCRIPTION
**Pull request by pmslavin**
Hello, fellow APTibians :)  I noticed that this bot was targeted at a much earlier release of irclib.  There have been a series of backwards-incompatible API changes since then, so I have updated it to use the current API as of 12.1.1.

The principle differences are:
1. A `NickMask` class' attributes replace the `nm_to_` functions.
2. The previous `Event.arguments` method is now an attribute that returns an iterable.
3.  `irc_lower` has been replaced with `irc.strings.lower()`.

I've also added an assignment (lines 277-8) to the `ServerConnection.buffer_class` that avoids an exception when a non-UTF8 byte is fed to the UTF8 decoder.  Without this, the bot will fail on servers (e.g. *.europa-irc.*) that return latin-1.

The `finally` block at line 53 caters for the circumstance where the first ever run is with the `--noadmin` option. The module db is then created, but it doesn't contain `admin` and this is never subsequently loaded.

I've tested things with a few of the modules, and all seems well.

### CODE REVIEW

**Comment by mossblaser** [comment]
@pmslavin Thank you very much :)

@j616 I believe you're responsible for running BeardBot in various places these days? Do you have some meaningful feedback on these changes? :) (And possibly the ability to try them out wherever you're hosting the old version). Thank you!

**Comment by pmslavin** [comment]
No problem - hope it proves useful.  In case you're wondering who on earth I am(!) - I'm that PostDoc who works with Graham Riley on his Met Office/HPC projects.  I'm based over in the Kilburn but am 'officially' in the APT.  I think I eventually arrived here when I was looking at some of Alan Stokes' SpiNNaker tools and became slightly distracted...

**Comment by tomjnixon** [comment]
Just given it a spin, and it's not obviously broken for me.

@mossblaser care to merge this? I don't have access.

**Comment by mossblaser** [comment]
Thank you very much all for your contributions and testing :).

**Pull request merged**
